BuyLog/buylog/buylog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from .views import *
from django.contrib.auth import views as auth_view
from django.conf import settings
from django.conf.urls.static import static
from scontrini.views import DemoStatsView

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r"^$|^\/$|^home\/$", home, name='landingpage'),
    path('scontrini/', include('scontrini.urls'), name='scontrini'),
    path('recensioni/', include('recensioni.urls'), name='recensioni'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('login/', auth_view.LoginView.as_view(), name='login'),
    path('logout/', auth_view.LogoutView.as_view(), name='logout'),
    path('user/', UserDetailView.as_view(), name='user'),
    # path('demo-stats/', DemoStatsView.as_view(), name='demo'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

BuyLog/buylog/recensioni/urls.py
from django.urls import path
from .views import RecensioniListView, NegozioRecensioniView, AggiungiRecensioneView, toggle_like

app_name = 'recensioni'

urlpatterns = [
    path('', RecensioniListView.as_view(), name='lista_recensioni'),
    path('negozio/<int:pk>/', NegozioRecensioniView.as_view(),
         name='recensioni_negozio'),
    path('aggiungi/<int:negozio_id>/',
         AggiungiRecensioneView.as_view(), name='aggiungi_recensione'),
    path('like/<int:review_id>/', toggle_like, name='toggle_like'),
]

BuyLog/buylog/recensioni/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from scontrini.models import Negozio
from django.utils import timezone


# Create your models here.

class Review(models.Model):
    utente = models.ForeignKey(User, on_delete=models.CASCADE)
    negozio = models.ForeignKey(
        Negozio, on_delete=models.CASCADE, related_name='recensioni')
    data = models.DateTimeField(default=timezone.now)

    # Valutazioni specifiche
    qualita_prezzo = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)],
        default=1
    )
    pulizia = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)],
        default=1
    )
    servizio = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)],
        default=1
    )
    varieta = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)],
        default=1
    )

    # Valutazione generale e commento
    voto_generale = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)],
        default=1
    )
    commento = models.TextField(max_length=300, null=True, blank=True)

    # Mi piace
    likes = models.ManyToManyField(
        User, related_name='recensioni_liked', blank=True)

    class Meta:
        verbose_name_plural = 'Reviews'
        ordering = ['-data']  # Ordina per data decrescente

    def __str__(self):
        return f"Recensione di {self.utente.username} per {self.negozio.nome}"

    def calcola_media(self):
        return (self.qualita_prezzo + self.pulizia + self.servizio + self.varieta + self.voto_generale) / 5

BuyLog/buylog/recensioni/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from .models import Review
from scontrini.models import Negozio
from django.urls import reverse_lazy
from django.db.models import Avg
from django.http import JsonResponse
from django.core.paginator import Paginator
from django.shortcuts import redirect
from django.urls import reverse
from django.db.models import Count
from django.utils import timezone

# Create your views here.


class RecensioniListView(ListView):
    model = Review
    template_name = 'recensioni/lista_recensioni.html'
    context_object_name = 'recensioni'
    paginate_by = 9

    def get_queryset(self):
        # Questo metodo sostituisce il queryset predefinito
        return Negozio.objects.annotate(
            num_recensioni=Count('recensioni'),
            media_recensioni=Avg('recensioni__voto_generale')
        ).order_by('-num_recensioni', '-media_recensioni')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Usa page_obj invece di sovrascrivere negozi
        context['negozi'] = context['page_obj']
        return context


class NegozioRecensioniView(DetailView):
    model = Negozio
    template_name = 'recensioni/recensioni_negozio.html'
    context_object_name = 'negozio'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        recensioni_list = Review.objects.filter(negozio=self.object)

        # Calcola la media delle recensioni
        media_recensioni = 0
        if recensioni_list.exists():
            media_recensioni = recensioni_list.aggregate(
                Avg('voto_generale'))['voto_generale__avg']
        context['media_recensioni'] = media_recensioni

        # Ordina per data o likes
        order_by = self.request.GET.get('order_by', '-data')
        context['current_order'] = order_by

        if order_by == 'likes':
            recensioni_list = recensioni_list.annotate(
                like_count=Count('likes')).order_by('-like_count', '-data')
        else:
            recensioni_list = recensioni_list.order_by('-data')

        paginator = Paginator(recensioni_list, 5)
        page = self.request.GET.get('page')
        context['recensioni'] = paginator.get_page(page)
        return context


class AggiungiRecensioneView(LoginRequiredMixin, CreateView):
    model = Review
    template_name = 'recensioni/aggiungi_recensione.html'
    fields = ['qualita_prezzo', 'pulizia', 'servizio', 'varieta',
              'voto_generale', 'commento']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        negozio = get_object_or_404(Negozio, pk=self.kwargs['negozio_id'])
        context['negozio'] = negozio

        # Controlla se esiste già una recensione
        existing_review = Review.objects.filter(
            utente=self.request.user,
            negozio=negozio
        ).first()

        if existing_review:
            context['existing_review'] = existing_review
            # Pre-popoliamo i campi con i valori esistenti
            for field in self.fields:
                context['initial_' + field] = getattr(existing_review, field)

        return context

    def form_valid(self, form):
        negozio = get_object_or_404(Negozio, pk=self.kwargs['negozio_id'])
        existing_review = Review.objects.filter(
            utente=self.request.user,
            negozio=negozio
        ).first()

        if existing_review:
            # Aggiorna la recensione esistente invece di crearne una nuova
            for field in self.fields:
                setattr(existing_review, field, form.cleaned_data[field])
            existing_review.data = timezone.now()  # Aggiorna la data con l'ultima modifica
            existing_review.likes.clear()  # Rimuove tutti i like
            existing_review.save()
            self.object = existing_review
        else:
            # Crea una nuova recensione
            self.object = form.save(commit=False)
            self.object.utente = self.request.user
            self.object.negozio = negozio
            self.object.save()

        return redirect(reverse('recensioni:recensioni_negozio', kwargs={'pk': negozio.id}))


@login_required
def toggle_like(request, review_id):
    review = get_object_or_404(Review, id=review_id)
    if request.user in review.likes.all():
        review.likes.remove(request.user)
        liked = False
    else:
        review.likes.add(request.user)
        liked = True
    return JsonResponse({
        'liked': liked,
        'likes_count': review.likes.count()
    })


def testfunc(request):
    print("TEST!!!")


def recensioni_negozio(request, negozio_id):
    negozio = get_object_or_404(Negozio, pk=negozio_id)
    recensioni_list = Review.objects.filter(negozio=negozio)

    # Calcola la media di tutte le valutazioni
    media_recensioni = 0
    if recensioni_list.exists():
        media_recensioni = sum(r.calcola_media()
                               for r in recensioni_list) / recensioni_list.count()

    # Ordina per data o likes
    order_by = request.GET.get('order_by', '-data')
    if order_by == 'likes':
        recensioni_list = recensioni_list.annotate(
            like_count=Count('likes')).order_by('-like_count', '-data')
    else:
        recensioni_list = recensioni_list.order_by('-data')

    paginator = Paginator(recensioni_list, 5)
    page = request.GET.get('page')
    recensioni = paginator.get_page(page)

    return render(request, 'recensioni/recensioni_negozio.html', {
        'negozio': negozio,
        'recensioni': recensioni,
        'media_recensioni': media_recensioni,
        'current_order': order_by
    })

BuyLog/buylog/recensioni/templates/recensioni/aggiungi_recensione.html
{% extends 'recensioni/base_recensioni.html' %}
{% load static %}

{% block recensioni_content %}
<div class="container mt-5">
    {% if existing_review %}
    <div class="alert alert-warning" role="alert">
        <h4 class="alert-heading">Attenzione!</h4>
        <p>Hai già scritto una recensione per questo negozio. Se procedi, la tua recensione precedente verrà sostituita con quella nuova.</p>
    </div>
    {% endif %}

    <h2 class="text-center mb-4">Scrivi una recensione per {{ negozio.nome }}</h2>
    
    <div class="row justify-content-center">
        <div class="col-md-8">
            <form method="post" id="recensioneForm">
                {% csrf_token %}
                {% if existing_review %}
                <input type="hidden" name="update_existing" value="true">
                {% endif %}
                
                <div class="rating-section mb-4">
                    <h5>Qualità/Prezzo</h5>
                    <div class="stars" data-rating="qualita_prezzo" data-initial-value="{{ initial_qualita_prezzo|default:0 }}">
                        {% for i in "12345" %}
                        <i class="far fa-star" data-value="{{ forloop.counter }}"></i>
                        {% endfor %}
                    </div>
                    <input type="hidden" name="qualita_prezzo" id="qualita_prezzo" required>
                </div>

                <div class="rating-section mb-4">
                    <h5>Pulizia</h5>
                    <div class="stars" data-rating="pulizia" data-initial-value="{{ initial_pulizia|default:0 }}">
                        {% for i in "12345" %}
                        <i class="far fa-star" data-value="{{ forloop.counter }}"></i>
                        {% endfor %}
                    </div>
                    <input type="hidden" name="pulizia" id="pulizia" required>
                </div>

                <div class="rating-section mb-4">
                    <h5>Servizio</h5>
                    <div class="stars" data-rating="servizio" data-initial-value="{{ initial_servizio|default:0 }}">
                        {% for i in "12345" %}
                        <i class="far fa-star" data-value="{{ forloop.counter }}"></i>
                        {% endfor %}
                    </div>
                    <input type="hidden" name="servizio" id="servizio" required>
                </div>

                <div class="rating-section mb-4">
                    <h5>Varietà</h5>
                    <div class="stars" data-rating="varieta" data-initial-value="{{ initial_varieta|default:0 }}">
                        {% for i in "12345" %}
                        <i class="far fa-star" data-value="{{ forloop.counter }}"></i>
                        {% endfor %}
                    </div>
                    <input type="hidden" name="varieta" id="varieta" required>
                </div>

                <div class="rating-section mb-4">
                    <h5>Voto Generale</h5>
                    <div class="stars" data-rating="voto_generale" data-initial-value="{{ initial_voto_generale|default:0 }}">
                        {% for i in "12345" %}
                        <i class="far fa-star" data-value="{{ forloop.counter }}"></i>
                        {% endfor %}
                    </div>
                    <input type="hidden" name="voto_generale" id="voto_generale" required>
                </div>

                <div class="form-group">
                    <label for="commento">Commento (opzionale, massimo 300 caratteri)</label>
                    <textarea class="form-control" name="commento" id="commento" rows="3" maxlength="300"></textarea>
                    <small class="text-muted">Caratteri rimanenti: <span id="char-count">300</span></small>
                    <div class="invalid-feedback">
                        Il commento non può superare i 300 caratteri.
                    </div>
                </div>

                <button type="submit" class="btn btn-primary mt-3">Invia Recensioneee</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

BuyLog/buylog/recensioni/templates/recensioni/base_recensioni.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    {{ block.super }}  <!-- Importante: mantiene il CSS del template padre -->
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    
    <!-- CSS specifico per recensioni -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block extra_js %}
    {{ block.super }} <!-- Importante: mantiene il JS del template padre (jQuery, Popper.js e Bootstrap.js) -->
    <script src="{% static 'js/recensioni.js' %}"></script>
    <script src="{% static 'js/stars.js' %}"></script>
    <script src="{% static 'js/commento.js' %}"></script>
{% endblock %}

{% block content %}
    {% block recensioni_content %}{% endblock %}
{% endblock %}

BuyLog/buylog/recensioni/templates/recensioni/lista_recensioni.html
{% extends 'recensioni/base_recensioni.html' %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center mb-4">Recensioni Supermercati</h1>
    
    <div class="row">
        {% for negozio in negozi %}
        <div class="col-md-4 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ negozio.nome }}</h5>
                    <div class="stars-container">
                        {% for i in "12345" %}
                            <i class="fas fa-star {% if i|add:'0' <= negozio.media_recensioni %}text-warning{% else %}text-muted{% endif %}"></i>
                        {% endfor %}
                    </div>
                    <p class="card-text">Media: {{ negozio.media_recensioni|floatformat:1 }}/5</p>
                    <a href="{% url 'recensioni:recensioni_negozio' negozio.id %}" class="btn btn-primary">Vedi Recensioni</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    
    <!-- Paginazione -->
    {% if negozi.paginator.num_pages > 0 %}
    <nav aria-label="Navigazione pagine" class="mt-4">
        <ul class="pagination justify-content-center">
            {% if negozi.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">&laquo; Prima</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ negozi.previous_page_number }}">Precedente</a>
                </li>
            {% endif %}

            {% for num in negozi.paginator.page_range %}
                {% if negozi.number == num %}
                    <li class="page-item active">
                        <span class="page-link">{{ num }}</span>
                    </li>
                {% elif num > negozi.number|add:'-3' and num < negozi.number|add:'3' %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            {% if negozi.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ negozi.next_page_number }}">Successiva</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ negozi.paginator.num_pages }}">Ultima &raquo;</a>
                </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{% endblock %}

BuyLog/buylog/recensioni/templates/recensioni/recensioni_negozio.html
{% extends 'recensioni/base_recensioni.html' %}

{% block recensioni_content %}
<div class="container mt-4">
    {% csrf_token %}
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="d-flex justify-content-between align-items-center mb-4">
                <h2>Recensioni per {{ negozio.nome }}</h2>
                <a href="{% url 'recensioni:aggiungi_recensione' negozio.id %}" class="btn btn-primary">
                    <i class="fas fa-plus"></i> Scrivi Recensione
                </a>
            </div>

            <!-- Media totale -->
            <div class="card mb-4">
                <div class="card-body text-center">
                    <h5 class="card-title">Valutazione Media</h5>
                    <div class="stars-container mb-2">
                        {% for i in "12345" %}
                            <i class="fas fa-star {% if i|add:'0' <= media_recensioni %}text-warning{% else %}text-muted{% endif %}"></i>
                        {% endfor %}
                    </div>
                    <p class="mb-0">{{ media_recensioni|floatformat:1 }}/5 basato su {{ recensioni.paginator.count }} recensioni</p>
                </div>
            </div>

            <!-- Lista recensioni -->
            <div class="mb-3">
                <div class="btn-group" role="group">
                    <a href="?order_by=-data" class="btn btn-outline-primary {% if not current_order or current_order == '-data' %}active{% endif %}">
                        <i class="fas fa-clock"></i> Più recenti
                    </a>
                    <a href="?order_by=likes" class="btn btn-outline-primary {% if current_order == 'likes' %}active{% endif %}">
                        <i class="fas fa-heart"></i> Più popolari
                    </a>
                </div>
            </div>

            <div class="mb-4">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Utente</th>
                            <th>Valutazione</th>
                            <th>Commento</th>
                            <th>Mi piace</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for recensione in recensioni %}
                        <tr class="recensione-row" data-toggle="modal" data-target="#recensioneModal{{ recensione.id }}" style="cursor: pointer;">
                            <td>{{ recensione.utente.username }}</td>
                            <td>
                                <div class="d-flex align-items-center">
                                    <div class="stars-container">
                                        {% for i in "12345" %}
                                            <i class="fas fa-star {% if i|add:'0' <= recensione.voto_generale %}text-warning{% else %}text-muted{% endif %}"></i>
                                        {% endfor %}
                                    </div>
                                </div>
                            </td>
                            <td>{{ recensione.commento|truncatechars:40 }}</td>
                            <td>
                                <button class="btn btn-link like-button p-0" data-review-id="{{ recensione.id }}" onclick="event.stopPropagation();">
                                    <i class="fas fa-thumbs-up {% if request.user in recensione.likes.all %}text-primary{% endif %}"></i>
                                    <span class="like-count">{{ recensione.likes.count }}</span>
                                </button>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <!-- Paginazione -->
            <div class="d-flex justify-content-center mt-4">
                <nav aria-label="Navigazione pagine">
                    <ul class="pagination">
                        {% if recensioni.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page=1">&laquo; Prima</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ recensioni.previous_page_number }}">Precedente</a>
                            </li>
                        {% endif %}

                        {% for num in recensioni.paginator.page_range %}
                            {% if recensioni.number == num %}
                                <li class="page-item active">
                                    <span class="page-link">{{ num }}</span>
                                </li>
                            {% else %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}

                        {% if recensioni.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ recensioni.next_page_number }}">Successiva</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ recensioni.paginator.num_pages }}">Ultima &raquo;</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>

<!-- Modals per ogni recensione -->
{% for recensione in recensioni %}
<div class="modal fade" id="recensioneModal{{ recensione.id }}" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Recensione di {{ recensione.utente.username }}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <h6>Valutazioni</h6>
                        <ul class="list-unstyled">
                            <li class="mb-2">
                                <strong>Qualità/Prezzo:</strong> 
                                <div class="stars-container d-inline">
                                    {% for i in "12345" %}
                                        <i class="fas fa-star {% if i|add:'0' <= recensione.qualita_prezzo %}text-warning{% else %}text-muted{% endif %}"></i>
                                    {% endfor %}
                                </div>
                            </li>
                            <li class="mb-2">
                                <strong>Pulizia:</strong>
                                <div class="stars-container d-inline">
                                    {% for i in "12345" %}
                                        <i class="fas fa-star {% if i|add:'0' <= recensione.pulizia %}text-warning{% else %}text-muted{% endif %}"></i>
                                    {% endfor %}
                                </div>
                            </li>
                            <li class="mb-2">
                                <strong>Servizio:</strong>
                                <div class="stars-container d-inline">
                                    {% for i in "12345" %}
                                        <i class="fas fa-star {% if i|add:'0' <= recensione.servizio %}text-warning{% else %}text-muted{% endif %}"></i>
                                    {% endfor %}
                                </div>
                            </li>
                            <li class="mb-2">
                                <strong>Varietà:</strong>
                                <div class="stars-container d-inline">
                                    {% for i in "12345" %}
                                        <i class="fas fa-star {% if i|add:'0' <= recensione.varieta %}text-warning{% else %}text-muted{% endif %}"></i>
                                    {% endfor %}
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <h6>Commento</h6>
                        <p>{{ recensione.commento }}</p>
                        <small class="text-muted">Pubblicato il {{ recensione.data|date:"d/m/Y H:i" }}</small>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}